---
  parser: babel-eslint
  parserOptions:
    experimentalObjectRestSpread: true
  plugins:
    - react
  env:
    es6: true
    browser: true
  extends:
    - plugin:react/recommended
    - airbnb
  rules:

    # personal preference
    space-before-function-paren:
      - error
      - never
    consistent-return:
      - off
    function-paren-newline:
      - error
      - consistent
    default-case:
      - error
      - commentPattern: ^no default$
    react/no-children-prop:
      - off

    # whatever you do in the privacy of your own home...
    no-underscore-dangle:
      - error
      - allowAfterThis: true

    # maybe temp... can lead to similar methods being confusingly seperated
    class-methods-use-this: off

    # for `#reduce` and such
    no-param-reassign:
      - error
      - ignorePropertyModificationsFor:
        - memo

    # allows destructuring omission and promotes clarity/debugging
    no-unused-vars:
      - error
      - ignoreRestSiblings: true
        argsIgnorePattern: ^_

    # react-router
    jsx-a11y/anchor-is-valid:
      - error
      - specialLink:
        - to

    # supports my extendedPropTypes.js
    react/no-typos: off

    # Dan Abramov says so: https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904
    react/jsx-filename-extension:
      - error
      - extensions:
        - .js

    # many components are easily id'd by certain prop
    react/jsx-first-prop-new-line: off

    # TEMP switching back/forth is slow early on
    react/prefer-stateless-function: off
    react/prop-types:
      - error
      - skipUndeclared: true
